### ISSUE TITLE
Telechargements en boucle

### ISSUE THREAD

**Issue by Syudagye** [Chaika9/paladiumlauncher#5]
**Bonjours,**
J'ai un petit problème avec le launcher : A chaque fois que je le relance, il me demande de retélécharger la version actuelle, même si je viens de le faire avant. 
Je voudrais donc savoir si c'est normal où sinon comment régler le problème.
Merci d'avance

**Comment by Wistaro** [comment]
Bonjour, 

tu as compilé toi-même les sources où tu utilises la dernière release?

**Comment by Syudagye** [comment]
C’était la dernière release mais apparemment ça a été réglé depuis le temps.
