### ISSUE TITLE
Pourquoi on autorise pas Linux et Mac ?

### ISSUE THREAD

**Issue by FaustinM** [Chaika9/paladiumlauncher#7]
Après plusieurs tests sur un pc avec linux, la seule partie non fonctionnel est le démarrage du jeu qui bloque sur un path

**Comment by Chaika9** [comment]
Car comme annoncé lors de la beta du nouveau launcher, seul la version Windows sera déployé pour facilité les choses. 
A sa sortie officiel, il sera déployé sur Linux et MacOS.

**Comment by FaustinM** [comment]
Mais peut-on supprimé l'avertissement bloquant ou juste le modifier pour devenir un message qui dit que la version est aux risques et périls de l'utilisateur

**Comment by Chaika9** [comment]
Oui mais je suis un des seul dev sur le launcher, il me semble pas savoir que tu est contributeur.
Donc il sera seulement pour Windows le temps de la beta.

**Comment by Chaika9** [comment]
Si tu est un joueur su Paladium, il te suffit d'utiliser la version Java pour jouer.

**Comment by Chaika9** [comment]
Le launcher est Open source pour la contribution.
Et non pour prendre le launcher pour un autre serveur.
L'open source n'est pas seulement pour prendre des programmes fait.

Après c'est peut être moi qui n'est pas compris ta demande. Dans ce cas, explique moi exactement pk cette demande. Merci ^^

**Comment by FaustinM** [comment]
Nan je compte pas voler votre travail ^^' mais m'impliquer dans le projet du launcher et malheureusement je me retrouve dans l'obligation de supprimer la condition de démarrage pour développer de mon côté ! J'aimerais donc savoir si je peux supprimer cette condition de démarrage sur le git afin de pouvoir coder plus simplement sur mon linux ! Après si c'est vraiment problématique et nécessaire afin d'éviter les demandes de support dans les autres systèmes pas de problème ! C'est pour ça que je préconise de remplacer le message bloquant par une popup d'avertissement.

Disponible sur discord si besoin : Faustin#8347

PS : Je cherche aussi un todo ou un cahier des charges :)

**Comment by Chaika9** [comment]
Pour une contribution au projet nous avons un discord pour ^^
Car je fait quelque vérif avant ^^
Contacte moi sur discord Chaika9#4451 pour si tu veux rejoindre.
Sinon pour le message je verrai si tu comptes vraiment faire de la contribution.

**Comment by FaustinM** [comment]
Je ne peux pas t'ajouter en ami :'( et pour des raisons que j'expliquerai en MP, il m'est impossible de te joindre autrement...

**Comment by Chaika9** [comment]
Tu peux maintenant
